---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: generate
  labels:
    app: generate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generate
  template:
    metadata:
      labels:
        app: generate
    spec:
      containers:
      - name: generate
        image: gcr.io/{{PROJECT}}/dataflow-demo-generate:latest